@extends('layouts.app')

@section('main')
{{--    <actividad-16d asset_audio="{{asset('audio')}}" route_back="{{route('normal.level-16.home')}}" route_next="{{route('normal.level-16.e')}}" asset_images="{{asset('images')}}"></actividad-16d>--}}

<layout-sudoku
        :number_of_activities="{{ 12 }}"
        :activity_number="{{ 4 }}"
        planet_1="{{ asset('images/planetas/tierra.svg') }}"
        planet_2="{{ asset('images/planetas/rojo.svg') }}"
        item_1="{{ asset('images/animales/leon.svg') }}"
        item_2="{{ asset('images/animales/cocodriloIcon.svg') }}"
        item_3="{{ asset('images/animales/elefanteIcon.svg') }}"
        color_1="red-600"
        color_2="blue-600"
        color_3="yellow-400"
        icon_1="icon-red1"
        icon_2="icon-blue"
        icon_3="icon-yellow"
        sound_item_1="{{asset('audio/voz1/animals/the/ElLeon.m4a')}}"
        sound_item_2="{{asset('audio/voz1/animals/the/ElCocodrilo.m4a')}}"
        sound_item_3="{{asset('audio/voz1/animals/the/ElElefante.m4a')}}"
        the_sound_item_1="{{asset('audio/voz1/colors/the/ElColorAzul.m4a')}}"
        the_sound_item_2="{{asset('audio/voz1/figures/the/ElCuadrado.m4a')}}"
        the_sound_item_3="{{asset('audio/voz1/letters/the/LaLetraC.m4a')}}"
        activity_description="Completa el cuadro sin repetir ningun Numero en fila o en columna"
        audio_win="{{asset('audio/voz1/win/fantastico1.m4a')}}"
        bg_color_activity="bg-circles-orange"
        border_color_activity="border-orange-600"
        palette_text="ANIMALES"
        asset_videos="{{asset('videos')}}"
        asset_audio="{{asset('audio')}}"
        route_back="{{route('normal.level-16.home')}}"
        route_next="{{route('normal.level-16.c')}}"
        asset_images="{{asset('images')}}"
        :sudoku_size="{{ 3 }}"
        introduction_audio_1="{{asset('audio/voz1/sudokus/vamoscompletar.m4a')}}"
        introduction_audio_2="{{asset('audio/voz1/sudokus/animals/comencemos.m4a')}}"
        caja_1=""
        caja_2="1"
        caja_3="2"
        caja_4="1"
        caja_5="2"
        caja_6=""
        caja_7=""
        caja_8="3"
        caja_9="1"
        :interactive_array="[1,7,6]"
        :interactive_array_solution="[3,2,3]"
        ok_audio_1="{{asset('audio/voz1/sudokus/animals/correctococodrilo.m4a')}}"
        ok_audio_2="{{asset('audio/voz1/sudokus/animals/bienelefante.m4a')}}"
        ok_audio_3=""
        ok_audio_4=""
        error_audio_1="{{asset('audio/voz1/sudokus/errors/parece.m4a')}}"
    >
    </layout-sudoku>
@endsection
