@extends('layouts.app')

@section('main')
{{--    <actividad-16f asset_audio="{{asset('audio')}}" route_back="{{route('normal.level-16.home')}}" route_next="{{route('normal.level-16.home')}}" asset_images="{{asset('images')}}"></actividad-16f>--}}

<layout-sudoku
        :number_of_activities="{{ 12 }}"
        :activity_number="{{ 1 }}"
        planet_1="{{ asset('images/planetas/tierra.svg') }}"
        planet_2="{{ asset('images/planetas/rojo.svg') }}"
        item_1="{{ asset('images/animales/tiburon.svg') }}"
        item_2="{{ asset('images/animales/cangrejo.svg') }}"
        item_3="{{ asset('images/animales/pulpo.svg') }}"
        color_1="blue-600"
        color_2="yellow-400"
        color_3="red-600"
        icon_1="icon-blue"
        icon_2="icon-yellow"
        icon_3="icon-red1"
        sound_item_1="{{asset('audio/voz1/colors/Azul.m4a')}}"
        sound_item_2="{{asset('audio/voz1/colors/Amarillo.m4a')}}"
        sound_item_3="{{asset('audio/voz1/colors/Rojo.m4a')}}"
        the_sound_item_1="{{asset('audio/voz1/colors/the/ElColorAzul.m4a')}}"
        the_sound_item_2="{{asset('audio/voz1/figures/the/ElCuadrado.m4a')}}"
        the_sound_item_3="{{asset('audio/voz1/letters/the/LaLetraC.m4a')}}"
        activity_description="Completa el cuadro sin repetir ningun Animal en fila o en columna"
        audio_win="{{asset('audio/voz1/win/fantastico1.m4a')}}"
        bg_color_activity="bg-circles-orange"
        border_color_activity="border-orange-600"
        palette_text="COLORES"
        asset_videos="{{asset('videos')}}"
        asset_audio="{{asset('audio')}}"
        route_back="{{route('normal.level-16.home')}}"
        route_next="{{route('normal.level-16.b')}}"
        asset_images="{{asset('images')}}"
        :sudoku_size="{{ 3 }}"
        introduction_audio_1="{{asset('audio/voz1/sudokus/inicios/vamoscolores.m4a')}}"
        introduction_audio_2="{{asset('audio/voz1/sudokus/inicios/ubicacolor.m4a')}}"
        caja_1=""
        caja_2="3"
        caja_3="1"
        caja_4=""
        caja_5="1"
        caja_6="2"
        caja_7="1"
        caja_8=""
        caja_9=""
        :interactive_array="[4,1,8,9]"
        :interactive_array_solution="[3,2,2,3]"
        ok_audio_1="{{asset('audio/voz1/sudokus/oks/erafaltante.m4a')}}"
        ok_audio_2="{{asset('audio/voz1/sudokus/oks/erafaltante.m4a')}}"
        ok_audio_3="{{asset('audio/voz1/sudokus/oks/erafaltante.m4a')}}"
        ok_audio_4="{{asset('audio/voz1/sudokus/oks/erafaltante.m4a')}}"
        error_audio_1="{{asset('audio/voz1/sudokus/errors/yaseencuentra.m4a')}}"
        error_audio_2="{{asset('audio/voz1/sudokus/errors/yaseencuentra.m4a')}}"
        error_audio_3="{{asset('audio/voz1/sudokus/errors/yaseencuentra.m4a')}}"
        error_audio_4="{{asset('audio/voz1/sudokus/errors/yaseencuentra.m4a')}}"
        :selector_1="[2,0]"
        :selector_2="[1,1]"
        :selector_3="[0,2]"
        :selector_4="[3,3]"
    >
    </layout-sudoku>
@endsection
