@extends('layouts.app')

@section('main')
    <layout-sudoku
        :number_of_activities="{{ 12 }}"
        :activity_number="{{ 12 }}"
        planet_1="{{ asset('images/planetas/tierra.svg') }}"
        planet_2="{{ asset('images/planetas/rojo.svg') }}"
        item_1="1"
        item_2="2"
        item_3="3"
        color_1=""
        color_2=""
        color_3=""
        icon_1="icon-blue"
        icon_2="icon-yellow"
        icon_3="icon-red1"
        sound_item_1="{{asset('audio/voz1/colors/Azul.m4a')}}"
        sound_item_2="{{asset('audio/voz1/figures/Cuadrado.m4a')}}"
        sound_item_3="{{asset('audio/voz1/letters/C.m4a')}}"
        the_sound_item_1="{{asset('audio/voz1/colors/the/ElColorAzul.m4a')}}"
        the_sound_item_2="{{asset('audio/voz1/figures/the/ElCuadrado.m4a')}}"
        the_sound_item_3="{{asset('audio/voz1/letters/the/LaLetraC.m4a')}}"
        activity_description="Completa el cuadro sin repetir ningun Numero en fila o en columna"
        audio_win="{{asset('audio/voz1/win/fantastico1.m4a')}}"
        bg_color_activity="bg-circles-orange"
        border_color_activity="border-orange-600"
        palette_text="NUMEROS"
        asset_videos="{{asset('videos')}}"
        asset_audio="{{asset('audio')}}"
        route_back="{{route('normal.level-16.k')}}"
        route_next="{{route('normal.level-16.home')}}"
        asset_images="{{asset('images')}}"
        :sudoku_size="{{ 3 }}"
        introduction_audio_1="{{asset('audio/voz1/permutaciones/vamoscolores.m4a')}}"
        caja_1=""
        caja_2="2"
        caja_3="1"
        caja_4=""
        caja_5="1"
        caja_6="3"
        caja_7="1"
        caja_8=""
        caja_9=""
        :interactive_array="[1,8,4,9]"
        :interactive_array_solution="[3,3,2,2]"
        ok_audio_1="{{asset('audio/voz1/win/brillante1.m4a')}}"
        ok_audio_2="{{asset('audio/voz1/win/fantastico1.m4a')}}"
        ok_audio_3="{{asset('audio/voz1/win/fantastico1.m4a')}}"
        ok_audio_4="{{asset('audio/voz1/win/fantastico1.m4a')}}"
        error_audio_1="{{asset('audio/voz1/colors/the/ElColorAzul.m4a')}}"
    >
    </layout-sudoku>

@endsection
